export enum GeneralFieldsEnum {
  REPRESENTATIVE = 'Código de representante',
  REPRESENTATIVE_NAME = 'Nombre del representante',
  LOCATION = 'Código de localidad',
  LOCATION_NAME = 'Localidad',
  LOCATION_ADDRESS = 'Dirección',
  LOCATION_POSTAL_CODE = 'Código postal',
  LOCATION_CITY = 'Ciudad',
  LOCATION_STATE = 'Estado',
  LOCATION_COUNTRY = 'País',
  LOCATION_LATITUDE = 'Latitude',
  LOCATION_LONGITUDE = 'Longitude',
  DATE = 'Fecha',
  NOTE = 'Nota',
  TAGS = 'Etiquetas',
  EMAIL = 'E-mail',
  PHONE = 'Teléfono',
  MOBILE = 'Móvil',
  STATUS = 'Estatus',
  REGISTERED = 'Registrado',
  START_DATE = 'Inicio de la visita',
  END_DATE = 'Final de la visita',
  DEALER_NAME = 'Distribuidor.Nombre del Distribuidor',
  OTHER_DEALER_NAME = 'Distribuidor.Nombre Otro Distribuidor',
  SELLER_NAME = 'Distribuidor.Nombre del Vendedor',
  MOBILE_SELLER = 'Distribuidor.Móbil Vendedor',
  EMAIL_SELLER = 'Distribuidor.E-mail Vendedor',
  NOTES_SELLER = 'Distribuidor.Notas del Distribuidor/Vendedor',
  LEGAL_NAME = 'Nombre Legal.Nombre Legal de la Empresa',
  FORM_LINK = 'Enlace al formulario',
}

export enum DatesFieldsEnum {
  SUBMISSION_DATE = 'Fecha',
  ACTIVATION_DATE = 'FECHA de la Activación',
  START_DATE = 'Inicio de la visita',
  END_DATE = 'Final de la visita',
  ACTIVATION_HOURS = 'Hora de INICIO y de TERMINO',
}
